//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyInfo
    {
        public int ID { get; set; }
        public string PropertyName { get; set; }
        public int PropertyTypeID { get; set; }
        public bool IsPrivateParkingAvailable { get; set; }
        public bool IsRoadSideParkingAvailable { get; set; }
        public bool IsNearToPublicTransport { get; set; }
        public bool IsNearToAirport { get; set; }
        public bool IsNearToRailwayStation { get; set; }
        public bool IsNearToBusStation { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
